name: bitnami/wordpress

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  wordpress:
    name: 'bitnami/wordpress'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build image
      run: |
        chmod +x /usr/sbin/install_packages
        cd bitnami-wordpress
        docker build --file Dockerfile -t registry.cn-hangzhou.aliyuncs.com/eggplant/bitnami-wordpress:latest .
    - name: Login to Aliyun registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}  
    - name: Push image to Aliyun
      run: docker push registry.cn-hangzhou.aliyuncs.com/eggplant/bitnami-wordpress:latest