name: bitnami/postgresql

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  postgresql:
    name: 'server:insiders'
    runs-on: ubuntu-latest
    steps:
    - name: Pull image from Docker Hub
      run: docker pull docker.io/bitnami/postgresql:14.5.0-debian-11-r0
    - name: Tag image
      run: docker tag docker.io/bitnami/postgresql:14.5.0-debian-11-r0 registry.cn-hangzhou.aliyuncs.com/eggplant/bitnami-postgresql:14.5.0-debian-11-r0
    - name: Login to Aliyun registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}  
    - name: Push image to Aliyun
      run: docker push registry.cn-hangzhou.aliyuncs.com/eggplant/bitnami-postgresql:14.5.0-debian-11-r0