name: kubesphere

on:
  workflow_dispatch:

jobs:
  postgresql:
    name: 'kubesphere'
    runs-on: ubuntu-latest
    steps:
    - name: Pull image from Docker Hub
      run: |
        docker pull docker.io/kubesphere/ks-installer:v3.3.1
        docker pull docker.io/kubesphere/ks-console:v3.3.1
        docker pull docker.io/kubesphere/ks-controller-manager:v3.3.1
        docker pull docker.io/kubesphere/ks-apiserver:v3.3.1
        docker pull docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4
    - name: Tag image
      run: |
        docker tag docker.io/kubesphere/ks-installer:v3.3.1 registry.cn-hangzhou.aliyuncs.com/eggplant/ks-installer:v3.3.1
        docker tag docker.io/kubesphere/ks-console:v3.3.1 registry.cn-hangzhou.aliyuncs.com/eggplant/ks-console:v3.3.1
        docker tag docker.io/kubesphere/ks-controller-manager:v3.3.1 registry.cn-hangzhou.aliyuncs.com/eggplant/ks-controller-manager:v3.3.1
        docker tag docker.io/kubesphere/ks-apiserver:v3.3.1 registry.cn-hangzhou.aliyuncs.com/eggplant/ks-apiserver:v3.3.1
        docker tag docker.io/mirrorgooglecontainers/defaultbackend-amd64:1.4 registry.cn-hangzhou.aliyuncs.com/eggplant/defaultbackend-amd64:1.4
    - name: Login to Aliyun registry
      uses: azure/docker-login@v1
      with:
        login-server: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}  
    - name: Push image to Aliyun
      run: |
        docker push registry.cn-hangzhou.aliyuncs.com/eggplant/ks-installer:v3.3.1
        docker push registry.cn-hangzhou.aliyuncs.com/eggplant/ks-console:v3.3.1
        docker push registry.cn-hangzhou.aliyuncs.com/eggplant/ks-controller-manager:v3.3.1
        docker push registry.cn-hangzhou.aliyuncs.com/eggplant/ks-apiserver:v3.3.1
        docker push registry.cn-hangzhou.aliyuncs.com/eggplant/defaultbackend-amd64:1.4